name: curso_list
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.2
  flutter_modular: ^3.4.1+1
  cloud_firestore: ^2.5.0
  google_sign_in: ^5.1.0
  animated_card: ^2.0.0
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  cpf_cnpj_validator: ^2.0.0
  easy_mask: ^2.0.1
  url_launcher: ^6.0.10
  flutter_typeahead: ^3.2.1


  
  

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/


